import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { LoginProvider } from "../Context/LoginContext";
import { HomeProvider } from "@/Context/HomeContext";
import { UnitProvider } from "@/Context/UnitContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html >
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <LoginProvider>
          <UnitProvider>
            <HomeProvider>{children}</HomeProvider>
          </UnitProvider>
        </LoginProvider>
      </body>
    </html>
  );
}
