import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { LoginProvider } from "../Context/LoginContext";
import { HomeProvider } from "@/Context/HomeContext";
import { UnitProvider } from "@/Context/UnitContext";
import { UtilityProvider } from "@/Context/UtilityContext";
import { HouseUnitProvider } from "@/Context/HouseUnitContext";
import { ProjectsProvider } from "@/Context/ProjectsDataContext";
import Nav from "./Components/Layout/Navbar/Nav";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html >
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <UtilityProvider>
          <LoginProvider>
            <ProjectsProvider>
              <UnitProvider>
                <HomeProvider>
                  <HouseUnitProvider>
                    <Nav />
                    {children}
                  </HouseUnitProvider>
                </HomeProvider>
              </UnitProvider>
            </ProjectsProvider>
          </LoginProvider>
        </UtilityProvider>
      </body>
    </html>
  );
}
